<?php
return array (
  'cron_entry.activitySummaryEmail' => 'Отправка сводки активности по email',
  'cron_entry.cleanUpDaily' => 'Ежедневная очистка',
  'cron_entry.cleanUpHourly' => 'Ежечасная очистка',
  'cron_entry.dailyStats' => 'Запись ежедневной статистики',
  'cron_entry.deleteExpiredBans' => 'Удаление истёкших блокировок',
  'cron_entry.downgradeExpired' => 'Обработка истёкших платных повышений прав пользователей',
  'cron_entry.emailBounce' => 'Обработка отказов в доставке почты',
  'cron_entry.emailUnsubscribe' => 'Обработка запросов на отмену подписки по электронной почте',
  'cron_entry.expireTempUserChanges' => 'Обработка истёкших временных изменений пользователя',
  'cron_entry.feeder' => 'RSS-ленты',
  'cron_entry.fileCheck' => 'Выполнение проверки целостности файлов',
  'cron_entry.forumStatistics' => 'Перестроение статистики форума',
  'cron_entry.memberStatsCache' => 'Перестроение кэшей статистики пользователей',
  'cron_entry.rebuildSearchForumCache' => 'Перестроение устаревших кэшей разделов поиска',
  'cron_entry.run_successfully' => 'Задание планировщика успешно выполнено.',
  'cron_entry.siropuChatBotMessages' => 'Чат: Публикация сообщения Бота',
  'cron_entry.siropuChatCleanActionLog' => 'Чат: Очистка журнала действий',
  'cron_entry.siropuChatIgnoredMessages' => 'Чат: Удалить игнорируемые сообщения',
  'cron_entry.siropuChatInactiveRooms' => 'Чат: Удалить неактивные комнаты',
  'cron_entry.siropuChatOlderMessages' => 'Чат: Удалить старые сообщения',
  'cron_entry.siropuChatRoomAutoPrune' => 'Чат: Автоматическая очистка комнаты',
  'cron_entry.siropuChatRoomUsers' => 'Чат: Обновления количества пользователей в комнате',
  'cron_entry.siropuChatSanctions' => 'Чат: Удалить наказания, которые закончились',
  'cron_entry.sitemap' => 'Перестроение карты сайта',
  'cron_entry.trophy' => 'Обновление трофеев пользователей',
  'cron_entry.userGroupPromotions' => 'Повышения прав групп',
  'cron_entry.views' => 'Обновление счётчиков просмотров',
  'cron_entry.warningExpiry' => 'Обработка истёкших предупреждений',
);