<?php
return array (
  'widget_pos.category_view_sidebar' => 'Просмотр категории: Боковая панель',
  'widget_pos.conversation_list_sidebar' => 'Список переписок: Боковая панель',
  'widget_pos.conversation_view_sidebar' => 'Просмотр переписки: Боковая панель',
  'widget_pos.find_threads_sidenav' => 'Поиск тем: боковая навигация',
  'widget_pos.forum_list_above_nodes' => 'Список разделов: Над узлами',
  'widget_pos.forum_list_below_nodes' => 'Список разделов: Под узлами',
  'widget_pos.forum_list_sidebar' => 'Список разделов: Боковая панель',
  'widget_pos.forum_new_posts_sidebar' => 'Новые сообщения: боковая навигация',
  'widget_pos.forum_overview_bottom' => 'Список разделов: внизу',
  'widget_pos.forum_overview_top' => 'Список разделов: сверху',
  'widget_pos.forum_view_sidebar' => 'Просмотр раздела: боковая панель',
  'widget_pos.help_page_sidenav' => 'Страница помощи: Боковая навигация',
  'widget_pos.member_view_sidebar' => 'Профиль пользователя: Боковая панель',
  'widget_pos.member_wrapper_sidenav' => 'Профиль пользователя: боковая навигация',
  'widget_pos.online_list_sidebar' => 'Список онлайн: Боковая панель',
  'widget_pos.pub_sidebar_bottom' => 'На всех страницах: Внизу боковой панели',
  'widget_pos.pub_sidebar_top' => 'На всех страницах: Вверху боковой панели',
  'widget_pos.siropu_chat_above_content' => 'Чат: Над содержимым',
  'widget_pos.siropu_chat_above_forum_list' => 'Чат: Над списком разделов форума',
  'widget_pos.siropu_chat_all_pages' => 'Чат: На всех страницах',
  'widget_pos.siropu_chat_below_breadcrumb' => 'Chat: Below breadcrumb',
  'widget_pos.siropu_chat_below_content' => 'Чат: Под содержимым',
  'widget_pos.siropu_chat_below_forum_list' => 'Чат: Под списком разделов форума',
  'widget_pos.siropu_chat_page' => 'Чат: Страница чата',
  'widget_pos.siropu_chat_page_sidebar' => 'Чат: Страница чата боковая панель',
  'widget_pos.siropu_chat_sidebar_bottom' => 'Чат: Под боковой панелью',
  'widget_pos.siropu_chat_sidebar_top' => 'Чат: Над боковой панелью',
  'widget_pos.thread_view_above_messages' => 'Просмотр темы: выше сообщений',
  'widget_pos.thread_view_below_messages' => 'Просмотр темы: ниже сообщений',
  'widget_pos.thread_view_below_quick_reply' => 'Просмотр темы: ниже быстрого ответа',
  'widget_pos.thread_view_sidebar' => 'Просмотр темы: Боковая панель',
  'widget_pos.whats_new_overview' => 'Что нового: Обзор',
  'widget_pos.whats_new_sidenav' => 'Что нового: Боковая навигация',
);