<?php
return array (
  'ad_pos.container_breadcrumb_bottom_above' => 'Контейнер хлебных крошек (нижний): выше',
  'ad_pos.container_breadcrumb_bottom_below' => 'Контейнер хлебных крошек (нижний): ниже',
  'ad_pos.container_breadcrumb_top_above' => 'Контейнер хлебных крошек (верхний): выше',
  'ad_pos.container_breadcrumb_top_below' => 'Контейнер хлебных крошек (верхний): ниже',
  'ad_pos.container_content_above' => 'Контейнер контента: выше',
  'ad_pos.container_content_below' => 'Контейнер контента: ниже',
  'ad_pos.container_header' => 'Контейнер шапки',
  'ad_pos.container_sidebar_above' => 'Контейнер боковой панели: выше',
  'ad_pos.container_sidebar_below' => 'Контейнер боковой панели: ниже',
  'ad_pos.container_sidenav_above' => 'Контейнер боковой навигации: выше',
  'ad_pos.container_sidenav_below' => 'Контейнер боковой навигации: ниже',
  'ad_pos.forum_overview_bottom' => 'Обзор форума: снизу',
  'ad_pos.forum_overview_top' => 'Обзор форума: сверху',
  'ad_pos.forum_view_above_node_list' => 'Просмотр форума: выше списка узлов',
  'ad_pos.forum_view_above_thread_list' => 'Просмотр форума: выше списка тем',
  'ad_pos.forum_view_below_node_list' => 'Просмотр форума: ниже списка узлов',
  'ad_pos.forum_view_below_stickies' => 'Просмотр форума: ниже списка закреплённых тем',
  'ad_pos.forum_view_below_thread_list' => 'Просмотр форума: ниже списка тем',
  'ad_pos.member_view_below_tabs' => 'Просмотр пользователя: ниже вкладок',
  'ad_pos.post_above_content' => 'Сообщение: выше содержимого сообщения',
  'ad_pos.post_below_container' => 'Сообщение: ниже контейнера сообщения',
  'ad_pos.post_below_content' => 'Сообщение: ниже содержимого сообщения',
  'ad_pos.thread_view_above_messages' => 'Просмотр темы: выше списка сообщений',
  'ad_pos.thread_view_below_messages' => 'Просмотр темы: ниже списка сообщений',
);