<?php
return array (
  'cron_entry.activitySummaryEmail' => 'Отправка сводки активности по email',
  'cron_entry.cleanUpDaily' => 'Ежедневная очистка',
  'cron_entry.cleanUpHourly' => 'Ежечасная очистка',
  'cron_entry.dailyStats' => 'Запись ежедневной статистики',
  'cron_entry.deleteExpiredBans' => 'Удаление истёкших блокировок',
  'cron_entry.downgradeExpired' => 'Обработка истёкших платных повышений прав пользователей',
  'cron_entry.emailBounce' => 'Обработка отказов в доставке почты',
  'cron_entry.emailUnsubscribe' => 'Обработка запросов на отмену подписки по электронной почте',
  'cron_entry.expireTempUserChanges' => 'Обработка истёкших временных изменений пользователя',
  'cron_entry.feeder' => 'RSS-ленты',
  'cron_entry.fileCheck' => 'Выполнение проверки целостности файлов',
  'cron_entry.forumStatistics' => 'Перестроение статистики форума',
  'cron_entry.memberStatsCache' => 'Перестроение кэшей статистики пользователей',
  'cron_entry.rebuildSearchForumCache' => 'Перестроение устаревших кэшей разделов поиска',
  'cron_entry.run_successfully' => 'Задание планировщика успешно выполнено.',
  'cron_entry.siropuChatBotMessages' => 'Chat: Post bot messages',
  'cron_entry.siropuChatCleanActionLog' => 'Chat: Clean action log',
  'cron_entry.siropuChatIgnoredMessages' => 'Chat: Delete ignored messages',
  'cron_entry.siropuChatInactiveRooms' => 'Chat: Delete inactive rooms',
  'cron_entry.siropuChatOlderMessages' => 'Chat: Delete older messages',
  'cron_entry.siropuChatRoomAutoPrune' => 'Chat: Room auto-prune',
  'cron_entry.siropuChatRoomUsers' => 'Chat: Update room user count',
  'cron_entry.siropuChatSanctions' => 'Chat: Delete expired sanctions',
  'cron_entry.sitemap' => 'Перестроение карты сайта',
  'cron_entry.trophy' => 'Обновление трофеев пользователей',
  'cron_entry.userGroupPromotions' => 'Повышения прав групп',
  'cron_entry.views' => 'Обновление счётчиков просмотров',
  'cron_entry.warningExpiry' => 'Обработка истёкших предупреждений',
);