<?php
return array (
  'option_group.acp' => 'Панель управления администратора',
  'option_group.alerts' => 'Оповещения и уведомления пользователей',
  'option_group.appearance' => 'Внешний вид',
  'option_group.attachments' => 'Вложения',
  'option_group.basicBoard' => 'Основные настройки',
  'option_group.boardActive' => 'Открытие и закрытие форума',
  'option_group.censoringOptions' => 'Автоцензор',
  'option_group.debug' => 'Настройки режима отладки',
  'option_group.discourager' => 'Нежелательные пользователи и дисциплина',
  'option_group.discussionOptions' => 'Темы, обсуждения и переписки',
  'option_group.emailOptions' => 'Настройки электронной почты',
  'option_group.imageLinkProxy' => 'Проксирование изображений и ссылок',
  'option_group.logging' => 'Настройки журналов',
  'option_group.mediaEmbedding' => 'Вставка медиа',
  'option_group.messageOptions' => 'Сообщения',
  'option_group.newsfeed' => 'Новостные ленты',
  'option_group.nodeList' => 'Список узлов и разделов форума',
  'option_group.performance' => 'Система и производительность',
  'option_group.pwa' => 'Настройки PWA',
  'option_group.searchOptions' => 'Настройки поиска',
  'option_group.seo' => 'Поисковая оптимизация (SEO)',
  'option_group.serviceProviders' => 'Внешние поставщики служб',
  'option_group.sharing' => 'Поделиться контентом в социальных сетях',
  'option_group.siropuChat' => 'Chat',
  'option_group.sitemap' => 'Генерация XML-карты сайта',
  'option_group.spam' => 'Управление спамом',
  'option_group.stats' => 'Статистика и метрики',
  'option_group.tagging' => 'Теги',
  'option_group.users' => 'Настройки пользователя',
  'option_group.usersAndRegistration' => 'Регистрация пользователей',
);