<?php
return array (
  'widget_pos_desc.category_view_sidebar' => 'Позиция в боковой панели шаблона category_view. Шаблон виджета может получать текущий объект <code>{$context.category}</code> в качестве контекста. Эти виджеты будут видны только в том случае, если включена опция "Создавать страницы для категорий".',
  'widget_pos_desc.conversation_list_sidebar' => 'Позиция в боковой панели при просмотре списка переписок.',
  'widget_pos_desc.conversation_view_sidebar' => 'Позиция в боковой панели шаблона \'conversation_view\' (просмотр переписки). Шаблон виджета может получать текущий объект <code>{$context.conversation}</code> в качестве контекста.',
  'widget_pos_desc.find_threads_sidenav' => 'Позиция внутри боковой навигации, на странице "Поиск тем". Отображается только тогда, когда <i>Внешний вид &gt; Настройки стиля &gt; Разное &gt; Стиль навигации страницы "Поиск тем"</i> имеет значение "Боковая навигация"',
  'widget_pos_desc.forum_list_above_nodes' => 'Позиция внутри основной области контента списка разделов над деревом узлов.',
  'widget_pos_desc.forum_list_below_nodes' => 'Позиция внутри основной области контента списка разделов под деревом узлов.',
  'widget_pos_desc.forum_list_sidebar' => 'Позиция в боковой панели списка разделов для отображения различной статистики и виджетов с новым контентом.',
  'widget_pos_desc.forum_new_posts_sidebar' => 'Позиция в боковой панели страницы \'Новые сообщения\' для отображения различной статистики и виджетов с новым контентом. Примечание: Эта страница доступна только в том случае, если настройка "Страница форума по умолчанию" установлена в значение "Новые сообщения".',
  'widget_pos_desc.forum_overview_bottom' => 'Позиция в нижней части страницы обзора разделов или страницы списка новых сообщений, если она установлен в качестве целевой страницы форума по умолчанию.',
  'widget_pos_desc.forum_overview_top' => 'Позиция в верхней части страницы обзора разделов или страницы списка новых сообщений, если она установлена в качестве целевой страницы форума по умолчанию.',
  'widget_pos_desc.forum_view_sidebar' => 'Позиция в боковой панели при просмотре списка тем или подразделов родительского раздела. Шаблон виджета может получать текущий объект <code>{$context.forum}</code> в качестве контекста.',
  'widget_pos_desc.help_page_sidenav' => 'Позиция внутри боковой навигации страниц помощи, под блоком навигации. Виджеты здесь будут появляться в мобильном меню (off-canvas) на узких дисплеях.',
  'widget_pos_desc.member_view_sidebar' => 'Позиция в боковой панели при просмотре профиля пользователя. Шаблон виджета может получать текущий объект <code>{$context.user}</code> в качестве контекста.',
  'widget_pos_desc.member_wrapper_sidenav' => 'Позиция внутри панели боковой навигации на страницы \'Выдающиеся пользователи\'.',
  'widget_pos_desc.online_list_sidebar' => 'Позиция внутри боковой панели страницы \'Сейчас на форуме\'.',
  'widget_pos_desc.pub_sidebar_bottom' => 'Положение виджета, которое отображается в нижней части всех публичных страниц. Специфичные виджеты всегда будут отображаться над этой позицией.',
  'widget_pos_desc.pub_sidebar_top' => 'Позиция виджета, которая отображается в верхней части всех публичных страниц. Специфичные виджеты всегда будут отображаться под этой позицией.',
  'widget_pos_desc.siropu_chat_above_content' => 'Position for Chat by Siropu.',
  'widget_pos_desc.siropu_chat_above_forum_list' => 'Position for Chat by Siropu.',
  'widget_pos_desc.siropu_chat_all_pages' => 'Position for Chat by Siropu.',
  'widget_pos_desc.siropu_chat_below_breadcrumb' => 'Position for Chat by Siropu.',
  'widget_pos_desc.siropu_chat_below_content' => 'Position for Chat by Siropu.',
  'widget_pos_desc.siropu_chat_below_forum_list' => 'Position for Chat by Siropu.',
  'widget_pos_desc.siropu_chat_page' => 'Dedicated chat page.',
  'widget_pos_desc.siropu_chat_page_sidebar' => 'Sidebar position for chat page.',
  'widget_pos_desc.siropu_chat_sidebar_bottom' => 'Position for Chat by Siropu.',
  'widget_pos_desc.siropu_chat_sidebar_top' => 'Position for Chat by Siropu.',
  'widget_pos_desc.thread_view_above_messages' => 'Позиция в области основного контента темы, над сообщениями. Шаблон виджета может получать текущий объект <code>{$context.thread}</code> в качестве контекста.',
  'widget_pos_desc.thread_view_below_messages' => 'Позиция в области основного контента темы, под сообщениями. Шаблон виджета может получать текущий объект <code>{$context.thread}</code> в качестве контекста.',
  'widget_pos_desc.thread_view_below_quick_reply' => 'Позиция в области основного контента темы, под формой быстрого ответа. Шаблон виджета может получать текущий объект <code>{$context.thread}</code> в качестве контекста.',
  'widget_pos_desc.thread_view_sidebar' => 'Позиция в боковой панели при просмотре темы. Шаблон виджета может получать текущий объект <code>{$context.thread}</code> в качестве контекста.',
  'widget_pos_desc.whats_new_overview' => 'Позиция внутри шаблона whats_new для отображения новых и недавних событий. Это занимает основную колонку, поэтому может поддерживать более большие виджеты.',
  'widget_pos_desc.whats_new_sidenav' => 'Позиция внутри боковой навигации, на странице "Что нового", под блоком навигации. Виджеты здесь будут появляться в мобильном меню (off-canvas) на узких дисплеях.',
);