<?php
return array (
  'alert_opt_out.conversation_message_reaction' => 'Отреагировал на Ваше сообщение в переписке',
  'alert_opt_out.post_forumwatch_insert' => 'Оставил сообщение в отслеживаемом разделе',
  'alert_opt_out.post_insert' => 'Ответил в отслеживаемой теме',
  'alert_opt_out.post_mention' => 'Упомянул Вас в сообщении',
  'alert_opt_out.post_quote' => 'Процитировал Ваше сообщение',
  'alert_opt_out.post_reaction' => 'Отреагировал на Ваше сообщение',
  'alert_opt_out.profile_post_comment_other_commenter' => 'Также прокомментировал(а) сообщение профиля',
  'alert_opt_out.profile_post_comment_reaction' => 'Отреагировал на комментарий к сообщению в Вашем профиле',
  'alert_opt_out.profile_post_comment_your_post' => 'Прокомментировал Ваше сообщение в профиле другого пользователя',
  'alert_opt_out.profile_post_comment_your_profile' => 'Оставил комментарий на странице Вашего профиля или к статусу',
  'alert_opt_out.profile_post_insert' => 'Оставил сообщение в Вашем профиле',
  'alert_opt_out.profile_post_mention' => 'Упомянул Вас в сообщении профиля или комментарии',
  'alert_opt_out.profile_post_reaction' => 'Отреагировал на сообщение в Вашем профиле',
  'alert_opt_out.siropu_chat_conv_message_reaction' => 'Reacts to your chat conversation message',
  'alert_opt_out.siropu_chat_room_message_reaction' => 'Reacts to your chat room message',
  'alert_opt_out.trophy_award' => 'Вы получаете новый трофей',
  'alert_opt_out.user_following' => 'Стал Вашим подписчиком',
);