<?php
return array (
  'nav._default' => 'По умолчанию (без выбранной вкладки)',
  'nav.contributedThreads' => 'Темы с Вашими сообщениями',
  'nav.currentVisitors' => 'Сейчас на форуме',
  'nav.defaultLatestActivity' => 'Недавняя активность',
  'nav.defaultLogOut' => 'Выйти',
  'nav.defaultNewsFeed' => 'Ваша лента новостей',
  'nav.defaultRegister' => 'Регистрация',
  'nav.defaultYourAccount' => 'Ваша учётная запись',
  'nav.defaultYourProfile' => 'Ваш профиль',
  'nav.findThreads' => 'Поиск тем',
  'nav.forumList' => 'Список разделов',
  'nav.forums' => 'Форум',
  'nav.home' => 'Главная',
  'nav.latestActivity' => 'Недавняя активность',
  'nav.markForumsRead' => 'Отметить разделы прочитанными',
  'nav.members' => 'Пользователи',
  'nav.newPosts' => 'Новые сообщения',
  'nav.newProfilePosts' => 'Новые сообщения в профиле',
  'nav.registeredMembers' => 'Зарегистрированные пользователи',
  'nav.searchForums' => 'Поиск по форуму',
  'nav.searchProfilePosts' => 'Поиск сообщений в профиле',
  'nav.siropuChat' => 'Чат',
  'nav.siropuChatArchive' => 'Архив',
  'nav.siropuChatSanctions' => 'Наказания',
  'nav.siropuChatTopChatters' => 'Топ пользователей',
  'nav.unansweredThreads' => 'Темы без ответов',
  'nav.watched' => 'Отслеживаемые',
  'nav.watchedForums' => 'Отслеживаемые разделы',
  'nav.watchedThreads' => 'Отслеживаемые темы',
  'nav.webID' => 'Вернуться на сайт объявлений Tataxon.uz',
  'nav.whatsNew' => 'Что нового',
  'nav.whatsNewNewsFeed' => 'Ваша лента новостей',
  'nav.whatsNewPosts' => 'Новые сообщения',
  'nav.whatsNewProfilePosts' => 'Новые сообщения в профиле',
  'nav.yourThreads' => 'Ваши темы',
);