<?php
return array (
  'style_prop_group.avatar' => 'Аватары',
  'style_prop_group.basic' => 'Основные настройки',
  'style_prop_group.bbCode' => 'Элементы BB-кодов',
  'style_prop_group.block' => 'Блоки',
  'style_prop_group.borderSpacing' => 'Рамки и отступы',
  'style_prop_group.button' => 'Кнопки',
  'style_prop_group.color' => 'Основные цвета',
  'style_prop_group.content' => 'Области контента',
  'style_prop_group.dataList' => 'Списки данных',
  'style_prop_group.email' => 'Электронная почта',
  'style_prop_group.fonts' => 'Типографика',
  'style_prop_group.footer' => 'Нижний колонтитул (футер)',
  'style_prop_group.form' => 'Формы',
  'style_prop_group.headerNav' => 'Шапка и навигация',
  'style_prop_group.inlineMod' => 'Встроенная модерация',
  'style_prop_group.input' => 'Формы ввода',
  'style_prop_group.member' => 'Профили пользователей',
  'style_prop_group.menu' => 'Всплывающие меню',
  'style_prop_group.message' => 'Сообщения',
  'style_prop_group.misc' => 'Разное',
  'style_prop_group.nodeList' => 'Список узлов/разделов',
  'style_prop_group.overlay' => 'Всплывающие окна',
  'style_prop_group.page' => 'Параметры страницы',
  'style_prop_group.palette' => 'Цветовая палитра',
  'style_prop_group.rte' => 'Полнофункциональный редактор',
  'style_prop_group.siropuChat' => 'Чат',
  'style_prop_group.tab' => 'Вкладки',
  'style_prop_group.tooltip' => 'Всплывающие подсказки',
);