<?php
return array (
  'widget.forum_overview_forum_statistics' => '',
  'widget.forum_overview_members_online' => '',
  'widget.forum_overview_new_posts' => '',
  'widget.forum_overview_new_profile_posts' => '',
  'widget.forum_overview_share_page' => '',
  'widget.latest_followed_profile_posts' => 'Сообщения профилей подписчиков',
  'widget.latest_posts' => 'Новые сообщения',
  'widget.latest_profile_posts' => 'Сообщения профилей',
  'widget.latest_watched' => 'Последнее отслеживаемое',
  'widget.member_wrapper_find_member' => '',
  'widget.member_wrapper_newest_members' => '',
  'widget.online_list_online_statistics' => '',
  'widget.siropu_chat' => '',
  'widget.siropu_chat_rooms' => '',
  'widget.siropu_chat_top_chatters' => '',
  'widget.siropu_chat_users' => '',
  'widget.unread_posts' => 'Непрочитанные сообщения',
  'widget.whats_new_new_posts' => '',
  'widget.whats_new_new_profile_posts' => '',
);